#!/usr/bin/zsh

fif() {
    if let $#==0 
    then
        echo "find in files - pass a file extension and text to search for"
        echo "usage: fif ext searchtext"
    else
        local theExt=$1
        shift
        echo "find . -name \"*${theExt}\" -type f -exec grep -nH --color=auto \"$@\" {} \;"
        find . -name "*${theExt}" -type f -exec grep -nH --color=auto "$@" {} \;
    
    fi
}

