#!/usr/bin/env zsh
#
#vim stuff

# To use with ConqueTerm or other basic terms
case $TERM in (vt100|rxvt)
    export ZSH_THEME="dst"
esac

function gvl() { gvim --serverlist "$*"}
function gv() { 
    gvim --servername $1 --remote-send ":vs<RETURN>"
    gvim --servername $1 --remote-silent $2 
    }
function gvt() { gvim --servername $1 --remote-tab-silent $*[2,-1] }
function gva() { gvim --servername $1 $*[2,-1] }

function todevel() { scp $1 brian@10.25.80.62: }
function fromdevel() { scp brian@10.25.80.62:$1 . }

if [[ -a ~/.gvm/bin/gvm-init.sh ]]; then
    source ~/.gvm/bin/gvm-init.sh
fi

function docker-volume-backup-compressed() {
  docker run --rm -v /tmp:/backup --volumes-from "$1" debian:jessie tar -czvf /backup/backup.tar.gz "${@:2}"
}
# restore files from /tmp/backup.tar.gz into a docker volume
function docker-volume-restore-compressed() {
    docker run --rm -v ~/.tmp:/backup --volumes-from "$1" debian:jessie tar -xzvf /backup/backup.tar.gz "${@:2}"
    echo "Double checking files..."
    docker run --rm -v /tmp:/backup --volumes-from "$1" debian:jessie ls -lh "${@:2}"
}
# backup files from a docker volume into /tmp/backup.tar
function docker-volume-backup() {
    docker run --rm -v /tmp:/backup --volumes-from "$1" busybox tar -cvf /backup/backup.tar "${@:2}"
}
# restore files from /tmp/backup.tar into a docker volume
function docker-volume-restore() {
    docker run --rm -v /tmp:/backup --volumes-from "$1" busybox tar -xvf /backup/backup.tar "${@:2}"
    echo "Double checking files..."
    docker run --rm -v /tmp:/backup --volumes-from "$1" busybox ls -lh "${@:2}"
}
